#
# Makefile for SPL assignments
#

DIRS = Aufgabe1 Aufgabe2 Aufgabe3 Aufgabe4 Aufgabe5 Aufgabe6 Aufgabe7

all:

clean:
		for i in $(DIRS) ; do rm -f $$i/*~ ; done
		rm -f *~

dist-clean:
		for i in $(DIRS) ; do rm -f $$i/*~ ; done
		rm -f *~
